In [1]:
from __future__ import division, print_function, absolute_import

import numpy as np
import tensorflow as tf
import logging
from DataPrep.data_io import DataFormatter
from nn.load_params import layer_name, convShape, getWeights
from nn.utils import getTriplets
from nn.model import initNetwork

logging.basicConfig(level=logging.DEBUG, filename="logfile.log", filemode="w",
                    format="%(asctime)-15s %(levelname)-8s %(message)s")

In [2]:
def reset_graph():  # Reset the graph
    if 'sess' in globals() and sess:
        sess.close()
    tf.reset_default_graph()

## GET INCEPTION WEIGHTS

In [3]:
parentPath = "/Users/sam/All-Program/App-DataSet/Deep-Neural-Nets/Models/FaceNet-Inception"
moduleWeightDict = getWeights(parentPath)

## INITIALIZE NETWORK WITHWEIGHTS

In [4]:
tensorDict = initNetwork(moduleWeightDict)

inpTensor  (?, 96, 96, 3)


## LOAD THE BATCH DATA:

In [4]:
path_to_batch_data = '/Users/sam/All-Program/App-DataSet/DeepFaceRecognition/data_models/batch_img_arr'
batch_file_name = 'random_batches.pickle'

dataX, dataY, labelDict = DataFormatter.getPickleFile(folderPath=path_to_batch_data, 
                                                      picklefileName=batch_file_name, getStats=True)
tensorDict = initNetwork(moduleWeightDict)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for batchNum, batchX in enumerate(dataX):
        batchY = dataY[batchNum, :]
        encodings = sess.run([tensorDict['output']], feed_dict={tensorDict['inpTensor']:batchX})
        
        print (X.eval())
        tripletIndexArr = getTriplets(X.eval(), img_per_label=3, num_labels=2, alpha=0.01)
        tripletIndexArr = np.array(tripletIndexArr).reshape(-1,3)
        a_idxs = tripletIndexArr[:,0].flatten()
        p_idxs = tripletIndexArr[:,1].flatten()
        n_idxs = tripletIndexArr[:,2].flatten()
        loss = tripletLoss(tf.gather(X, a_idxs),
                           tf.gather(X, p_idxs),
                           tf.gather(X, n_idxs), alpha=0.2)

        print (loss.eval())

The shape of input data (X) is:  (10, 18, 96, 96, 3)
The shape of input data (Y) is:  (10, 18)
Unique labels in dataY is:  [ 0.  1.  2.]
Label dict:  None
[ 0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1.  2.  2.  2.  2.  2.  2.]


In [42]:
import tensorflow as tf
import numpy as np
np.random.seed(1)
tfdata = tf.cast(np.random.rand(1,1,3,5) + 10, dtype=tf.float32)
print (tfdata.get_shape().as_list())
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    batchMean, batchVar = tf.nn.moments(tfdata, axes=[0,1,2], name="moments")
    print (tfdata.eval())
    print (batchMean.eval())
    print (batchMean.get_shape().as_list())
    print (batchVar.eval())
    print (batchVar.get_shape().as_list())

[1, 1, 3, 5]
[[[[ 10.41702175  10.72032452  10.00011444  10.30233288  10.14675617]
   [ 10.09233856  10.18626022  10.34556103  10.39676762  10.53881645]
   [ 10.41919422  10.68521976  10.20445251  10.87811756  10.02738762]]]]
[ 10.30951786  10.5306015   10.18337631  10.52573872  10.23765373]
[5]
[ 0.02358428  0.05949085  0.020111    0.06357152  0.0477244 ]
[5]


In [44]:
np.array([1,2,3,4])[-1]

4

In [12]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]],
                 [[3, 3, 3], [4, 4, 4]],
                 [[5, 5, 5], [6, 6, 6]]])

a = tf.constant([[1,2,3],[3,2,4],[1,1,4]])
print(t.shape)
print (a.shape)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print (tf.gather(a, [0, 1]).eval())



(3, 2, 3)
(3, 3)
[[1 2 3]
 [3 2 4]]


In [13]:
pow(0.3426 - 0.927, 2) + pow(0.7484-0.62853, 2)

0.3558921769